### ISSUE TITLE
Custom Adapter

### ISSUE THREAD

**Issue by sohayb** [avast/android-styled-dialogs#102]
Hello,
Are you planning to add custom adapter rather than just setting items? for, let's say, items having images in addition to titles.
Thanks

**Comment by destil** [comment]
Hi, it makes sense to add this functionality to `ListDialogFragment`. We don't plan to do it, but we would accept a pull request.

Just beware that it's tricky, because Adapter needs a Context for inflating it's views. And you don't want to leak Activity Context after a configuration change (rotation). So the custom Adapters would probably need to implement some interface which would take care of setting the Context.

**Comment by syrakozz** [comment]
+1

**Comment by destil** [comment]
@sohayb Any updates regarding to a pull request?

**Comment by sohayb** [comment]
I'm sorry, but didn't have any time to implement that :/

**Comment by destil** [comment]
And do you thing you will find time?

**Comment by sohayb** [comment]
Unfortunately I can't give a definitive answer :(

**Comment by destil** [comment]
I'm trying to clean up issues. So let's close it and feel free to reopen if you find time.
